[package]
name = "abc178"
version = "0.1.0"
authors = ["Kousuke Takaki <u7693@protonmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
