[dependencies.procon]
git = "https://github.com/u7693/procon"

[package]
authors = ['Kousuke Takaki <u7693@protonmail.com>']
edition = '2018'
name = 'abc153'
version = '0.1.0'
[profile.release]
lto = true
panic = 'abort'
