[package]
name = "procon"
version = "0.1.0"
authors = ["Kousuke Takaki <u7693@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-snippet = "0.6"
